#!/bin/bash

# Enter Host Details and User Details.

REGION=$region
CITY=$city
USERNAME=$username
PASSWORD=$password


# Set Timezone
ln -sf /usr/share/zoneinfo/$region/$city /etc/localtime
hwclock --systohc

# Set Locale
sed -i 's/^#en_US.UTF-8 UTF-8/en_US.UTF-8 UTF-8/' /etc/locale.gen
locale-gen

touch /etc/locale.conf
echo LANG=en_US.UTF-8 >> /etc/locale.conf

# 